deployment:
  tasks:
    - export DEPLOYPATH=/home/kantggjb/oms/ 
    - /bin/cp -r accounts $DEPLOYPATH
    - /bin/cp -r membership $DEPLOYPATH
    - /bin/cp -r general $DEPLOYPATH
    - /bin/cp -r static $DEPLOYPATH
    - /bin/cp -r templates $DEPLOYPATH
