# Generated by Django 4.2.7 on 2023-12-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralAndLifetimeMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_type",
                    models.CharField(
                        choices=[("G", "General"), ("L", "Lifetime")], max_length=1
                    ),
                ),
                ("name_of_applicant", models.CharField(max_length=200)),
                ("dob", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=1,
                    ),
                ),
                ("nationality", models.CharField(max_length=200)),
                ("issued_from", models.CharField(max_length=200)),
                ("permanent_address", models.CharField(max_length=200)),
                ("affiliation", models.CharField(max_length=200)),
                ("citizenship_card_no", models.CharField(max_length=20)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("BE", "*BE/Equivalent"),
                            ("ME", "*ME/Equivalent"),
                            ("PHD", "PHD/Equivalent"),
                        ],
                        max_length=3,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("passed_year", models.CharField(blank=True, max_length=4, null=True)),
                ("pp_photo", models.ImageField(upload_to="")),
                ("citizenship", models.ImageField(upload_to="")),
                ("masters_document", models.ImageField(upload_to="")),
                ("work_experience", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionalMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_address", models.CharField(max_length=200)),
                ("registration_no", models.CharField(max_length=200)),
                ("company_documents", models.ImageField(upload_to="")),
                ("working_field", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=200)),
            ],
        ),
    ]
