# Generated by Django 4.2.7 on 2023-12-04 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalandlifetimemembership",
            old_name="country",
            new_name="phd_country",
        ),
        migrations.RenameField(
            model_name="generalandlifetimemembership",
            old_name="institution",
            new_name="phd_institution",
        ),
        migrations.RenameField(
            model_name="generalandlifetimemembership",
            old_name="passed_year",
            new_name="phd_passed_year",
        ),
        migrations.RenameField(
            model_name="generalandlifetimemembership",
            old_name="subject",
            new_name="phd_subject",
        ),
        migrations.RemoveField(
            model_name="generalandlifetimemembership",
            name="degree",
        ),
        migrations.RemoveField(
            model_name="institutionalmembership",
            name="company_documents",
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="be_country",
            field=models.CharField(default="ss", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="be_institution",
            field=models.CharField(default="ss", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="be_passed_year",
            field=models.CharField(default="ss", max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="be_subject",
            field=models.CharField(default="ss", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="me_country",
            field=models.CharField(default="dd", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="me_institution",
            field=models.CharField(default="ss", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="me_passed_year",
            field=models.CharField(default="dd", max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="me_subject",
            field=models.CharField(default="ss", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="institutionalmembership",
            name="company_document",
            field=models.ImageField(default="ss", upload_to="institutional_documents"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institutionalmembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institutionalmembership",
            name="pan_document",
            field=models.ImageField(default="ss", upload_to="institutional_documents"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institutionalmembership",
            name="registration_document",
            field=models.ImageField(default="ss", upload_to="institutional_documents"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institutionalmembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
