# Generated by Django 4.2.7 on 2023-12-05 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "membership",
            "0002_rename_country_generalandlifetimemembership_phd_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="created_by",
            field=models.OneToOneField(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_and_lifetime_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institutionalmembership",
            name="created_by",
            field=models.OneToOneField(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institutional_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
