# Generated by Django 4.2.7 on 2023-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_alter_generalandlifetimemembership_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalandlifetimemembership",
            name="nationality",
            field=models.CharField(max_length=2),
        ),
    ]
