# Generated by Django 4.2.7 on 2023-12-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0009_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionalmembership",
            name="verification",
            field=models.BooleanField(default=False),
        ),
    ]
