# Generated by Django 4.2.7 on 2023-12-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0010_institutionalmembership_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="verification",
            field=models.BooleanField(default=False),
        ),
    ]
