# Generated by Django 4.2.7 on 2023-12-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0011_generalandlifetimemembership_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionalmembership",
            name="contact_number",
            field=models.CharField(default="9999967898", max_length=10),
            preserve_default=False,
        ),
    ]
