# Generated by Django 4.2.7 on 2023-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0014_payment_created_at_payment_paid_amount_in_paisa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paid",
            field=models.BooleanField(default=True),
        ),
    ]
