# Generated by Django 4.2.7 on 2023-12-10 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0015_payment_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
