# Generated by Django 4.2.7 on 2023-12-11 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0019_institutionalmembership_reject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institutionalmembership",
            old_name="reject",
            new_name="rejected",
        ),
    ]
