# Generated by Django 4.2.7 on 2023-12-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0020_rename_reject_institutionalmembership_rejected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionalmembership",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
