# Generated by Django 4.2.7 on 2023-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0021_alter_institutionalmembership_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
