# Generated by Django 4.2.7 on 2023-12-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0023_alter_generalandlifetimemembership_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
