# Generated by Django 4.2.7 on 2023-12-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0024_alter_payment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="verified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institutionalmembership",
            name="verified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
