# Generated by Django 4.2.7 on 2023-12-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership",
            "0027_generalandlifetimemembership_country_of_institution_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="college_id_card",
            field=models.ImageField(default="ss", upload_to="students"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="generalandlifetimemembership",
            name="membership_type",
            field=models.CharField(
                choices=[("G", "General"), ("L", "Lifetime"), ("S", "Student")],
                max_length=1,
            ),
        ),
    ]
