# Generated by Django 4.2.7 on 2023-12-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0028_generalandlifetimemembership_college_id_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="membership_since",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
