# Generated by Django 4.2.7 on 2023-12-25 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership",
            "0031_payment_paid_by_phone_payment_pidx_payment_txn_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paid_by_phone",
            new_name="paid_by_mobile",
        ),
    ]
