# Generated by Django 4.2.7 on 2023-12-25 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0032_rename_paid_by_phone_payment_paid_by_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_by_mobile",
        ),
    ]
