# Generated by Django 4.2.7 on 2023-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0033_remove_payment_paid_by_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paypal_payer_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
