# Generated by Django 4.2.7 on 2023-12-30 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0036_alter_generalandlifetimemembership_issued_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                (
                    "groups_mail",
                    models.ManyToManyField(
                        related_name="groups_mail", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
