# Generated by Django 4.2.7 on 2023-12-30 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0037_storemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreateGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "custom_users",
                    models.ManyToManyField(
                        related_name="create_group_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
