# Generated by Django 4.2.7 on 2023-12-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0039_alter_creategroups_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="creategroups",
            name="mail_status",
            field=models.CharField(
                choices=[("S", "Sent"), ("D", "Draft")], default="D", max_length=1
            ),
        ),
    ]
