# Generated by Django 4.2.7 on 2024-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0042_storemail_associated_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalandlifetimemembership',
            name='upgrade_request',
            field=models.BooleanField(default=False),
        ),
    ]
