# Generated by Django 4.2.7 on 2024-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0044_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalandlifetimemembership',
            name='upgrade_request',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
