# Generated by Django 4.1 on 2024-01-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0045_alter_generalandlifetimemembership_upgrade_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalandlifetimemembership',
            name='masters_document',
            field=models.FileField(upload_to='general_and_lifetime_documents'),
        ),
    ]
