# Generated by Django 4.1 on 2024-01-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0046_alter_generalandlifetimemembership_masters_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="be_university",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="me_university",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="generalandlifetimemembership",
            name="phd_university",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="company_document",
            field=models.FileField(upload_to="institutional_documents"),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="pan_document",
            field=models.FileField(upload_to="institutional_documents"),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="registration_document",
            field=models.FileField(upload_to="institutional_documents"),
        ),
    ]
