# Generated by Django 4.2.7 on 2023-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(default="admin", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("A", "Admin"), ("U", "User")], default="A", max_length=1
            ),
            preserve_default=False,
        ),
    ]
