# Generated by Django 4.2.7 on 2023-12-04 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_full_name_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
    ]
