# Generated by Django 4.2.7 on 2023-12-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(default="ww33", max_length=200),
            preserve_default=False,
        ),
    ]
