# Generated by Django 4.2.7 on 2023-12-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_customuser_is_verified_customuser_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedPinNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin", models.IntegerField(unique=True)),
            ],
        ),
    ]
