# Generated by Django 5.0 on 2023-12-24 07:22

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_generatedpinnumber_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[config.validators.validate_phone]),
        ),
    ]
